apiVersion: v1
kind: Service
metadata:
  name: kube-capabilities-demo
  labels:
    name: kube-capabilities-demo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    name: kube-capabilities-demo
  containerPort: 80