apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-capabilities-demo
  labels:
    name: kube-capabilities-demo
spec:
  replicas: 1
  selector:
    name: kube-capabilities-demo
  template:
    metadata:
      labels:
        name: kube-capabilities-demo
    spec:
      containers:
#      - name: httpd
#        image: httpd
      - name: httpd-nano
        ####################
        # This works but I’d like to figure out a way
        # to do this where we don’t have to push to
        # a repo first - just use the locally built
        # docker image to deploy to kube.
        ####################
        image: finn0013/httpd-nano 
        ports:
        - containerPort: 80


